import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const youngSerif = localFont({
  src: "./fonts/YoungSerif-Regular.ttf",
  variable: "--font-young-serif",
  weight: "400",
});
const Outfit = localFont({
  src: "./fonts/Outfit-VariableFont_wght.ttf",
  variable: "--font-outfit",
  weight: "400 600 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${youngSerif.variable} ${Outfit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
